modLoader = "javafml"
loaderVersion = "[4,)"
license = "Insert License Here"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Aristotle's Comedy"
authors = "Solstice"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
displayURL="https://github.com/Solstace-MC/Aristotles-Comedy"
#logoFile = ""

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "biolith"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "aristotles_comedy.mixins.json"
